"""Added inventory table

Revision ID: 5ff56fe54eb4
Revises: eeb1c65f808f
Create Date: 2025-02-28 15:28:01.232820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff56fe54eb4'
down_revision: Union[str, None] = 'eeb1c65f808f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
