"""included BU to products

Revision ID: 65ccae899c7d
Revises: ab2537e65e8c
Create Date: 2025-04-29 16:26:56.085187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ccae899c7d'
down_revision: Union[str, None] = 'ab2537e65e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unidad_de_negocio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'unidad_de_negocio')
    # ### end Alembic commands ###
