"""cambio orders

Revision ID: d314cfdc08a4
Revises: 427bfd471963
Create Date: 2025-04-22 08:27:16.353312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd314cfdc08a4'
down_revision: Union[str, None] = '427bfd471963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('isv', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('final_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'final_price')
    op.drop_column('orders', 'isv')
    # ### end Alembic commands ###
