"""Fixed Inventory-Product relationship

Revision ID: eeb1c65f808f
Revises: 2ccf111d7120
Create Date: 2025-02-28 15:02:26.372535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb1c65f808f'
down_revision: Union[str, None] = '2ccf111d7120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
